data-platform:
  outputs:
    dev:
      account: '{{ env_var(''ACCOUNT'') }}'
      database: DWH
      role: DATA-TEAM
      schema:  '{{ env_var(''USER_SCHEMA'') }}'
      threads: 1
      type: snowflake
      user: '{{ env_var(''SNOWFLAKE_USER'') }}'
      warehouse: '{{ env_var(''EAREHOUSE'') }}'
  target: dev